# Konfigurasi Nginx untuk Dev Environment
# File: /etc/nginx/conf.d/dev.conf (di VM Dev)
server {
    listen 80;
    server_name dev.partner-onboarding.alita.id;

    location / {
        proxy_pass http://localhost:3001;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
    }
}

# ---------------------------------------------------------

# Konfigurasi Nginx untuk Prod Environment
# File: /etc/nginx/conf.d/prod.conf (di VM Prod)
server {
    listen 80;
    server_name partner-onboarding.alita.id;

    location / {
        proxy_pass http://localhost:3000;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
    }
}
