name: Deploy Development

on:
  push:
    branches:
      - dev

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install Dependencies
        run: npm ci

      # - name: Lint Check
      #   run: npm run lint

  deploy:
    needs: test
    runs-on: [self-hosted, dev]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Deploy
        run: |
          cd /var/www/Partner-Team-Onboarding-Web
          git pull origin dev
          npm install
          npx drizzle-kit generate
          npx drizzle-kit migrate
          npm run build
          pm2 restart partner-onboarding
