name: Deploy Development

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: [self-hosted, dev]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Deploy
        run: |
          cd /var/www/Partner-Team-Onboarding-Web
          git fetch origin
          git reset --hard origin/dev
          docker compose -f docker-compose.dev.yml down
          docker compose -f docker-compose.dev.yml up -d --build
          docker image prune -f
