name: Deploy Development

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: [self-hosted, dev]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Deploy
        run: |
          cd /var/www/Partner-Team-Onboarding-Web
          git fetch origin
          git reset --hard origin/dev
          docker compose -f docker-compose.dev.yml up -d --build
          docker compose -f docker-compose.dev.yml --profile migration run --rm migration sh -c "npm run db:generate && npm run db:migrate"
          docker image prune -f
